version: '3'
services:
    nginx-proxy-pw:
        container_name: container-nginx-proxy-pw
        image: jwilder/nginx-proxy
        ports:
            - "10:80"
            - "3001:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro

    pwadmin:
        container_name: container-  
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./web:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    
        ports:
            - "8082:80"    

        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysql

        links:
            - mysql
            - php
        tty: true
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: container-phpmyadmin-pw
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            PMA_HOST: ${MYSQL_HOST}
        restart: always
        depends_on:
            - mysql
        links:
            - mysql

        ports:
            - "9191:80"  
    mysql:
        container_name: ${MYSQL_HOST}
        image: mysql:${MYSQL_VERSION}
        restart: always
        env_file:
            - ".env"
        environment:
            MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "8990:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"

    php:
        image: nanoninja/php-fpm:latest
        volumes:
            - "./web:/var/www/html"
        container_name: container-php-pw
        restart: always
        tty: true